name: clean
description: Showcase project

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  tch_appliable_core: ^0.6.3
  tch_common_widgets: ^0.6.3

  url_launcher: ^6.0.6

  cupertino_icons: ^1.0.2

  flutter_svg: ^0.22.0

  custom_refresh_indicator: ^1.0.0

  pull_to_refresh: ^2.0.0

  flutter_secure_storage: ^4.2.0

  maps_launcher: ^2.0.0

  google_maps_flutter: ^2.0.6

  package_info: ^2.0.2

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/mockUpData/authorization/
    - assets/mockUpData/forgotPassword/
    - assets/mockUpData/jobDetails/
    - assets/mockUpData/jobLists/

  fonts:
    - family: Open Sans Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Open Sans SemiBold
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: Open Sans SemiBold Italic
      fonts:
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
    - family: Open Sans Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
    - family: Open Sans Bold Italic
      fonts:
        - asset: fonts/OpenSans-BoldItalic.ttf
    - family: Open Sans Extra Bold
      fonts:
        - asset: fonts/OpenSans-ExtraBold.ttf
    - family: Open Sans Extra Bold Italic
      fonts:
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
    - family: Open Sans Italic
      fonts:
        - asset: fonts/OpenSans-Italic.ttf
    - family: Open Sans Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf
    - family: Open Sans Light
      fonts:
        - asset: fonts/OpenSans-Light.ttf
    - family: Open Sans Light Italic
      fonts:
        - asset: fonts/OpenSans-LightItalic.ttf
    - family: Iter
      fonts:
        - asset: fonts/Inter-Regular.ttf
